Repository TremboBoys/Freela_Frontend, pull requests merged in 2024-10, with the labels that each got.

#76 Feat 44
  public/imagens/email-icon.png
  public/imagens/email.png
  public/imagens/medal-icon.png
  public/imagens/padlock-icon.png
  public/imagens/pencil-icon.png
  public/imagens/person-icon.png
  public/imagens/security-icon.png
  public/public.md
  src/assets/Sass/configProfile/_configInputs.scss
  src/assets/Sass/configProfile/_configProfile.scss
  src/assets/Sass/configProfile/_personalInformation.scss
  src/assets/Sass/configProfile/_sideBar.scss
  src/assets/Sass/configProfile/_skillsTable.scss
  src/assets/images/configProfile/email-icon.png
  src/assets/images/configProfile/medal-icon.png
  src/assets/images/configProfile/padlock-icon.png
  src/assets/images/configProfile/pencil-icon.png
  src/assets/images/configProfile/person-icon.png
  src/assets/images/configProfile/security-icon.png
  src/components/configProfile/ConfigProfile.vue
  src/components/configProfile/SideBar.vue
  src/components/configProfile/email/EmailConfig.vue
  src/components/configProfile/password/PasswordConfig.vue
  src/components/configProfile/personalInformation/ConfigInputs.vue
  src/components/configProfile/personalInformation/PersonalInformationConfig.vue
  src/components/configProfile/personalInformation/SkillsTable.vue
  src/components/configProfile/security/SecurityConfig.vue
  src/components/configProfile/subscriptionPlan/SubscriptionPlanConfig.vue
  src/components/index.js
  src/router/index.js
  src/views/plan/SubscriptionPlanView.vue
  src/views/user/ConfigurationUserView.vue
Labels: enhancement

#86 refactor-85
  .env
  .eslintrc.js
  dev-dist/sw.js
  package-lock.json
  package.json
  src/components/index.js
  src/composables/useAuthStatus.js
  src/services/auth2/auth.js
  src/stores/auth2/auth.js
  src/views/user/SignInUserView.vue
  src/views/user/SignUpUserView.vue
  vite.config.js
  vue.config.js
Labels: refactor

#95 Feat 77
  public/imagens/email-icon.png
  public/imagens/email.png
  public/imagens/medal-icon.png
  public/imagens/padlock-icon.png
  public/imagens/pencil-icon.png
  public/imagens/person-icon.png
  public/imagens/security-icon.png
  src/assets/Sass/configProfile/_passwordInputs.scss
  src/assets/Sass/configProfile/_sendButton.scss
  src/assets/Sass/freelancer/_searchArea.scss
  src/components/configProfile/SideBar.vue
  src/components/configProfile/password/PasswordConfig.vue
  src/components/configProfile/password/SendButton.vue
  src/components/configProfile/password/passwordInputs.vue
  src/components/freelancer/SearchArea.vue
Labels: enhancement

#90 FEAT: Finish received proposal page #89.
  src/assets/Sass/project/_project.scss
  src/components/receivedProposal/ReceivedProposal.vue
  src/components/receivedProposal/ReceivedSearch.vue
  src/router/index.js
  src/views/proposal/ReceivedProposalView.vue
Labels: enhancement

#94 Feat 93
  package-lock.json
  package.json
  src/assets/Sass/payment/_paymentLayout.scss
  src/assets/Sass/payment/inputs/_inputNumber.scss
  src/assets/Sass/payment/inputs/_inputSelect.scss
  src/assets/Sass/payment/inputs/_inputText.scss
  src/assets/Sass/payment/inputs/_inputsPayment.scss
  src/assets/Sass/payment/send/_sendPayment.scss
  src/assets/Sass/payment/skills/_starRating.scss
  src/assets/Sass/payment/skills/_tableSkills.scss
  src/assets/Sass/payment/skills/_titleSkills.scss
  src/assets/Sass/payment/title/_titlePayment.scss
  src/components/payment/MakePayment.vue
  src/components/payment/inputs/InputNumber.vue
  src/components/payment/inputs/InputPayment.vue
  src/components/payment/inputs/InputSelect.vue
  src/components/payment/inputs/InputText.vue
  src/components/payment/inputs/InputsPayment.vue
  src/components/payment/send/SendPayment.vue
  src/components/payment/skills/RatingRow.vue
  src/components/payment/skills/StarRating.vue
  src/components/payment/skills/TableSkills.vue
  src/components/payment/skills/TitleSkills.vue
  src/components/payment/title/TitlePayment.vue
  src/main.js
  src/router/index.js
  src/views/payment/PaymentView.vue
Labels: enhancement

#92 FEAT: Finish "FinishedProject.vue" page #91.
  src/assets/Sass/finishedProject/_starRating.scss
  src/assets/Sass/finishedProject/_tableSkills.scss
  src/components/finishedProject/FinishedProject.vue
  src/components/finishedProject/inputs/InputNumber.vue
  src/components/finishedProject/inputs/InputPayment.vue
  src/components/finishedProject/inputs/InputSelect.vue
  src/components/finishedProject/inputs/InputText.vue
  src/components/finishedProject/inputs/InputsProject.vue
  src/components/finishedProject/send/SendProject.vue
  src/components/finishedProject/skills/RatingRow.vue
  src/components/finishedProject/skills/SkillsTable.vue
  src/components/finishedProject/skills/StarRating.vue
  src/components/finishedProject/skills/TableSkills.vue
  src/components/finishedProject/skills/TitleSkills.vue
  src/components/finishedProject/title/TitleProject.vue
  src/components/proposal/term/MaximumTerm.vue
  src/router/index.js
  src/views/project/FinishedProjectView.vue
Labels: enhancement

#99 Feat 78
  src/assets/Sass/configProfile/_emailConfig.scss
  src/assets/Sass/configProfile/_emailInputs.scss
  src/assets/Sass/configProfile/_passwordInputs.scss
  src/assets/images/configProfile/hide.png
  src/assets/images/configProfile/view.png
  src/components/configProfile/email/EmailConfig.vue
  src/components/configProfile/email/EmailInputs.vue
  src/components/configProfile/password/passwordInputs.vue
  src/main.js
Labels: enhancement

#98 Feat 36
  src/assets/Sass/plans/_planFree.scss
  src/assets/Sass/plans/_planMonthly.scss
  src/assets/Sass/plans/_planYear.scss
  src/assets/Sass/plans/_subscriptionPlans.scss
  src/assets/images/Crown.png
  src/assets/images/Medieval-Crown.png
  src/assets/images/Queen-Crown.png
  src/assets/images/discount.png
  src/assets/main.css
  src/components/plans/planFree.vue
  src/components/plans/planMonthly.vue
  src/components/plans/planYear.vue
  src/components/plans/subscriptionsPlans.vue
  src/views/plan/SubscriptionPlanView.vue
Labels: enhancement

#101 Feat 81
  src/assets/Sass/configProfile/_Bcards.scss
  src/assets/Sass/configProfile/_SubsArea.scss
  src/assets/Sass/configProfile/_subsTitle.scss
  src/assets/images/configProfile/crown.png
  src/components/configProfile/subscriptionPlan/BenefitsCard.vue
  src/components/configProfile/subscriptionPlan/SubsArea.vue
  src/components/configProfile/subscriptionPlan/SubsTitle.vue
  src/components/configProfile/subscriptionPlan/SubscriptionPlanConfig.vue
Labels: enhancement

#103 CHORE: Import content and table in SecurityConfig.vue #102
  src/assets/Sass/configProfile/_SecArea.scss
  src/assets/Sass/configProfile/_acessTable.scss
  src/assets/Sass/configProfile/_skillsTable.scss
  src/assets/images/configProfile/Brazilian-circle-flag.png
  src/assets/images/configProfile/trash-icon.png
  src/components/configProfile/security/AcessTable.vue
  src/components/configProfile/security/SecArea.vue
  src/components/configProfile/security/SecurityConfig.vue
Labels: enhancement

#109 Feat 80
  src/assets/Sass/configProfile/_codeVerification.scss
  src/assets/Sass/configProfile/_confPasswordTitles.scss
  src/assets/Sass/configProfile/_confirmationArea.scss
  src/components/configProfile/confirmation/CodeVerification.vue
  src/components/configProfile/confirmation/ConfEmailTitles.vue
  src/components/configProfile/confirmation/ConfPasswordTitles.vue
  src/components/configProfile/confirmation/ConfirmationEmail.vue
  src/components/configProfile/confirmation/ConfirmationPassword.vue
  src/components/configProfile/email/EmailInputs.vue
  src/components/configProfile/password/passwordInputs.vue
  src/router/index.js
  src/views/user/ConfirmationEmailUserView.vue
  src/views/user/ConfirmationPasswordUserView.vue
Labels: enhancement

#105 Feat 102
  src/assets/Sass/configProfile/_acessTable.scss
Labels: refactor

#113 Feat 57
  package-lock.json
  package.json
  src/assets/Sass/chat/chatMessage/_headerContact.scss
  src/assets/Sass/chat/chatMessage/_messageReceived.scss
  src/assets/Sass/chat/chatMessage/_messageSent.scss
  src/assets/Sass/chat/chatMessage/_selectedNone.scss
  src/assets/Sass/chat/chatMessage/_sendMessage.scss
  src/assets/Sass/chat/contacts/_asideContacts.scss
  src/assets/Sass/chat/contacts/_buttonSearch.scss
  src/assets/Sass/chat/contacts/_contactUser.scss
  src/assets/Sass/default/header/_defaultHeader.scss
  src/assets/Sass/default/header/_headerContainer.scss
  src/assets/images/chat/Mobile-Chat.png
  src/assets/images/chat/notification.png
  src/assets/images/chat/search.png
  src/components/chat/AsideContacts.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/chatMessage/HeaderContact.vue
  src/components/chat/chatMessage/MessageReceived.vue
  src/components/chat/chatMessage/MessageSent.vue
  src/components/chat/chatMessage/SelectedNone.vue
  src/components/chat/chatMessage/SendMessage.vue
  src/components/chat/contacts/ButtonSearch.vue
  src/components/chat/contacts/ContactUser.vue
  src/components/home/FreelaClient.vue
  src/views/chat/ChatView.vue
Labels: enhancement

#119 FIX: Adjust in router-link header default and header home #118.
  src/assets/Sass/dashboard/profile/_aboutMe.scss
  src/assets/Sass/default/header/_dropdown.scss
  src/components/default/header/LeftSide.vue
  src/components/default/header/RightSide.vue
  src/components/default/header/dropdowns/FoundJob.vue
  src/components/default/header/dropdowns/MyFinances.vue
  src/components/default/header/dropdowns/MyProjects.vue
  src/components/home/HeaderHome.vue
  src/router/index.js
Labels: enhancement

#121 FIX: Adjust in router-links proposal #120.
  src/assets/Sass/payment/send/_sendPayment.scss
  src/components/Projects/projectsSelect.vue
  src/components/proposal/ProposalConfirm.vue
  src/stores/chat/chat.js
Labels: enhancement

#123 Fix 122
  src/components/dashboard/profile/LogoName.vue
  src/components/dashboard/projects/projectProgress/CardProject.vue
Labels: enhancement

#125 FIX: Update router-link in LogoAndIcons and ulFooter components #124.
  src/components/default/footer/LogoAndIcons.vue
  src/components/default/footer/ulFooter.vue
Labels: enhancement

#126 Dev
  src/assets/Sass/dashboard/profile/_aboutMe.scss
  src/assets/Sass/default/header/_dropdown.scss
  src/assets/Sass/payment/send/_sendPayment.scss
  src/components/Projects/projectsSelect.vue
  src/components/dashboard/profile/LogoName.vue
  src/components/dashboard/projects/projectProgress/CardProject.vue
  src/components/default/footer/LogoAndIcons.vue
  src/components/default/footer/ulFooter.vue
  src/components/default/header/LeftSide.vue
  src/components/default/header/RightSide.vue
  src/components/default/header/dropdowns/FoundJob.vue
  src/components/default/header/dropdowns/MyFinances.vue
  src/components/default/header/dropdowns/MyProjects.vue
  src/components/home/HeaderHome.vue
  src/components/proposal/ProposalConfirm.vue
  src/router/index.js
  src/stores/chat/chat.js
Labels: enhancement

#129 Feat 128
  src/assets/Sass/project-registration/_complete-project-registration.scss
  src/assets/Sass/project-registration/_description-project-registration.scss
  src/assets/Sass/project-registration/_project-registration.scss
  src/assets/Sass/project-registration/_size-project-registration.scss
  src/assets/Sass/project-registration/_types-project-registration.scss
  src/assets/images/alert-circle.png
  src/assets/images/complete.png
  src/components/index.js
  src/components/registerProject/completeProject/CompleteProjectRegistration.vue
  src/components/registerProject/descriptionRegistration/DescriptionProjectRegistration.vue
  src/components/registerProject/projectRegistration/ProjectRegistration.vue
  src/components/registerProject/projectRegistration/RegisterDesign.vue
  src/components/registerProject/projectRegistration/RegisterOption.vue
  src/components/registerProject/projectRegistration/RegisterOption2.vue
  src/components/registerProject/projectRegistration/RegisterOption3.vue
  src/components/registerProject/projectRegistration/RegisterOption4.vue
  src/components/registerProject/projectRegistration/RegisterText.vue
  src/components/registerProject/sizeProject/SizeProjectRegistration.vue
  src/components/registerProject/typeProject/TypeProjectRegistration.vue
  src/router/index.js
  src/views/project/RegisterProjectView.vue
Labels: enhancement

#135 Refactor 131
  src/assets/Sass/default/footer/_FooterContainer.scss
  src/assets/Sass/default/footer/_defaultFooter.scss
  src/assets/Sass/default/footer/_logoAndIcons.scss
  src/assets/Sass/default/footer/_ulFooter.scss
  src/components/default/footer/ulFooter.vue
Labels: enhancement

#137 Dev
  src/assets/Sass/default/footer/_FooterContainer.scss
  src/assets/Sass/default/footer/_defaultFooter.scss
  src/assets/Sass/default/footer/_logoAndIcons.scss
  src/assets/Sass/default/footer/_ulFooter.scss
  src/assets/Sass/project-registration/_complete-project-registration.scss
  src/assets/Sass/project-registration/_description-project-registration.scss
  src/assets/Sass/project-registration/_project-registration.scss
  src/assets/Sass/project-registration/_size-project-registration.scss
  src/assets/Sass/project-registration/_types-project-registration.scss
  src/assets/images/alert-circle.png
  src/assets/images/complete.png
  src/components/default/footer/ulFooter.vue
  src/components/index.js
  src/components/registerProject/completeProject/CompleteProjectRegistration.vue
  src/components/registerProject/descriptionRegistration/DescriptionProjectRegistration.vue
  src/components/registerProject/projectRegistration/ProjectRegistration.vue
  src/components/registerProject/projectRegistration/RegisterDesign.vue
  src/components/registerProject/projectRegistration/RegisterOption.vue
  src/components/registerProject/projectRegistration/RegisterOption2.vue
  src/components/registerProject/projectRegistration/RegisterOption3.vue
  src/components/registerProject/projectRegistration/RegisterOption4.vue
  src/components/registerProject/projectRegistration/RegisterText.vue
  src/components/registerProject/sizeProject/SizeProjectRegistration.vue
  src/components/registerProject/typeProject/TypeProjectRegistration.vue
  src/main.js
  src/router/index.js
  src/views/project/RegisterProjectView.vue
Labels: enhancement

#138 Refactor 130
  src/assets/Sass/payment/_paymentLayout.scss
  src/assets/Sass/payment/inputs/_inputNumber.scss
  src/assets/Sass/payment/inputs/_inputSelect.scss
  src/assets/Sass/payment/inputs/_inputText.scss
  src/assets/Sass/payment/inputs/_inputsPayment.scss
  src/assets/Sass/payment/send/_sendPayment.scss
  src/assets/Sass/payment/skills/_starRating.scss
  src/assets/Sass/payment/skills/_tableSkills.scss
  src/assets/Sass/payment/skills/_titleSkills.scss
  src/assets/Sass/payment/title/_titlePayment.scss
  src/components/payment/MakePayment.vue
  src/components/payment/title/TitlePayment.vue
Labels: enhancement, refactor
