Repository TremboBoys/Freela_Frontend, pull requests merged in 2024-11, with the labels that each got.

#141 Refactor 139
  index.html
  src/assets/Sass/dashboard/_dashboardPage.scss
  src/assets/Sass/dashboard/profile/_aboutMe.scss
  src/assets/Sass/dashboard/profile/_favoriteArea.scss
  src/assets/Sass/dashboard/profile/_infoProfile.scss
  src/assets/Sass/dashboard/profile/_logoName.scss
  src/assets/Sass/dashboard/profile/_mainSkills.scss
  src/assets/Sass/dashboard/profile/_publicProfile.scss
  src/assets/Sass/dashboard/projects/completedProject/_cardProject.scss
  src/assets/Sass/dashboard/projects/completedProject/_container.scss
  src/assets/Sass/dashboard/projects/projectProgress/_cardProject.scss
  src/assets/Sass/dashboard/projects/projectProgress/_container.scss
  src/assets/main.css
  src/components/default/header/DefaultHeader.vue
  src/views/global/DashboardView.vue
Labels: enhancement, refactor

#143 REFACTOR: Responsiveness home page finish #142.
  src/assets/Sass/home/_freelaClient.scss
  src/assets/Sass/home/_headerHome.scss
  src/assets/Sass/home/_mainHome.scss
  src/assets/Sass/home/_talentsSkills.scss
  src/components/home/TalentsSkills.vue
Labels: enhancement, refactor

#147 Refactor 144
  src/assets/Sass/project/_project.scss
  src/components/default/header/DefaultHeader.vue
  src/components/receivedProposal/ReceivedProposal.vue
  src/views/proposal/ReceivedProposalView.vue
Labels: enhancement, refactor

#149 REFACTOR: Update adjust responsiveness home page #142.
  src/assets/Sass/home/_freelaClient.scss
  src/assets/Sass/home/_mainHome.scss
  src/assets/Sass/home/_talentsSkills.scss
Labels: bug, refactor

#150 Dev
  index.html
  src/assets/Sass/dashboard/_dashboardPage.scss
  src/assets/Sass/dashboard/profile/_aboutMe.scss
  src/assets/Sass/dashboard/profile/_favoriteArea.scss
  src/assets/Sass/dashboard/profile/_infoProfile.scss
  src/assets/Sass/dashboard/profile/_logoName.scss
  src/assets/Sass/dashboard/profile/_mainSkills.scss
  src/assets/Sass/dashboard/profile/_publicProfile.scss
  src/assets/Sass/dashboard/projects/completedProject/_cardProject.scss
  src/assets/Sass/dashboard/projects/completedProject/_container.scss
  src/assets/Sass/dashboard/projects/projectProgress/_cardProject.scss
  src/assets/Sass/dashboard/projects/projectProgress/_container.scss
  src/assets/Sass/finishedProject/_starRating.scss
  src/assets/Sass/finishedProject/_tableSkills.scss
  src/assets/Sass/home/_freelaClient.scss
  src/assets/Sass/home/_headerHome.scss
  src/assets/Sass/home/_mainHome.scss
  src/assets/Sass/home/_talentsSkills.scss
  src/assets/Sass/payment/_paymentLayout.scss
  src/assets/Sass/payment/inputs/_inputNumber.scss
  src/assets/Sass/payment/inputs/_inputSelect.scss
  src/assets/Sass/payment/inputs/_inputText.scss
  src/assets/Sass/payment/inputs/_inputsPayment.scss
  src/assets/Sass/payment/send/_sendPayment.scss
  src/assets/Sass/payment/skills/_starRating.scss
  src/assets/Sass/payment/skills/_tableSkills.scss
  src/assets/Sass/payment/skills/_titleSkills.scss
  src/assets/Sass/payment/title/_titlePayment.scss
  src/assets/Sass/project/_project.scss
  src/assets/main.css
  src/components/default/header/DefaultHeader.vue
  src/components/finishedProject/FinishedProject.vue
  src/components/finishedProject/inputs/InputNumber.vue
  src/components/finishedProject/inputs/InputPayment.vue
  src/components/finishedProject/inputs/InputSelect.vue
  src/components/finishedProject/inputs/InputText.vue
  src/components/finishedProject/inputs/InputsProject.vue
  src/components/finishedProject/send/SendProject.vue
  src/components/finishedProject/skills/RatingRow.vue
  src/components/finishedProject/skills/SkillsTable.vue
  src/components/finishedProject/skills/StarRating.vue
  src/components/finishedProject/skills/TableSkills.vue
  src/components/finishedProject/skills/TitleSkills.vue
  src/components/finishedProject/title/TitleProject.vue
  src/components/home/TalentsSkills.vue
  src/components/payment/MakePayment.vue
  src/components/payment/title/TitlePayment.vue
  src/components/receivedProposal/ReceivedProposal.vue
  src/views/global/DashboardView.vue
  src/views/proposal/ReceivedProposalView.vue
Labels: enhancement, refactor

#151 FIX: Update in bug responsiveness 1024px and add new responsiveness #…
  src/assets/Sass/dashboard/_dashboardPage.scss
  src/assets/Sass/dashboard/profile/_aboutMe.scss
  src/assets/Sass/dashboard/profile/_favoriteArea.scss
  src/assets/Sass/dashboard/profile/_infoProfile.scss
  src/assets/Sass/dashboard/profile/_logoName.scss
  src/assets/Sass/dashboard/profile/_mainSkills.scss
  src/assets/Sass/dashboard/profile/_publicProfile.scss
  src/assets/Sass/dashboard/projects/completedProject/_cardProject.scss
  src/assets/Sass/dashboard/projects/completedProject/_container.scss
  src/assets/Sass/dashboard/projects/projectProgress/_cardProject.scss
  src/assets/Sass/dashboard/projects/projectProgress/_container.scss
Labels: bug

#152 Refactor 148
  src/assets/Sass/configProfile/_configInputs.scss
  src/assets/Sass/configProfile/_configProfile.scss
  src/assets/Sass/configProfile/_sideBar.scss
  src/assets/Sass/configProfile/_skillsTable.scss
  src/components/configProfile/SideBar.vue
  src/components/configProfile/personalInformation/SkillsTable.vue
Labels: enhancement, refactor

#159 Refactor 158
  src/assets/Sass/configProfile/_Bcards.scss
  src/assets/Sass/configProfile/_SubsArea.scss
  src/assets/Sass/configProfile/_subsTitle.scss
  src/components/configProfile/ConfigProfile.vue
  src/components/default/header/DefaultHeader.vue
Labels: enhancement, refactor

#157 Refactor 156
  src/assets/Sass/configProfile/_passwordInputs.scss
Labels: enhancement, refactor

#155 Refactor 154
  src/assets/Sass/configProfile/_emailInputs.scss
Labels: enhancement, refactor

#164 Refactor 162
  src/assets/Sass/configProfile/_codeVerification.scss
  src/assets/Sass/configProfile/_confirmationArea.scss
Labels: enhancement, refactor

#170 Refactor 169
  src/assets/Sass/report/_buttonFreela.scss
  src/assets/Sass/report/_descriptionFreela.scss
  src/assets/Sass/report/_reportFreela.scss
  src/assets/Sass/report/_titleFreela.scss
  src/assets/Sass/report/_titleProject.scss
Labels: enhancement, refactor

#172 REFACTOR: Responsiveness popUp finish #171.
  src/assets/Sass/project/popUp/_popUp.scss
Labels: enhancement, refactor

#174 Dev
  src/assets/Sass/aboutUs/_mainPage.scss
  src/assets/Sass/aboutUs/_topPage.scss
  src/assets/Sass/configProfile/_Bcards.scss
  src/assets/Sass/configProfile/_SecArea.scss
  src/assets/Sass/configProfile/_SubsArea.scss
  src/assets/Sass/configProfile/_acessTable.scss
  src/assets/Sass/configProfile/_codeVerification.scss
  src/assets/Sass/configProfile/_configInputs.scss
  src/assets/Sass/configProfile/_configProfile.scss
  src/assets/Sass/configProfile/_confirmationArea.scss
  src/assets/Sass/configProfile/_emailInputs.scss
  src/assets/Sass/configProfile/_passwordInputs.scss
  src/assets/Sass/configProfile/_sideBar.scss
  src/assets/Sass/configProfile/_skillsTable.scss
  src/assets/Sass/configProfile/_subsTitle.scss
  src/assets/Sass/dashboard/_dashboardPage.scss
  src/assets/Sass/dashboard/profile/_aboutMe.scss
  src/assets/Sass/dashboard/profile/_favoriteArea.scss
  src/assets/Sass/dashboard/profile/_infoProfile.scss
  src/assets/Sass/dashboard/profile/_logoName.scss
  src/assets/Sass/dashboard/profile/_mainSkills.scss
  src/assets/Sass/dashboard/profile/_publicProfile.scss
  src/assets/Sass/dashboard/projects/completedProject/_cardProject.scss
  src/assets/Sass/dashboard/projects/completedProject/_container.scss
  src/assets/Sass/dashboard/projects/projectProgress/_cardProject.scss
  src/assets/Sass/dashboard/projects/projectProgress/_container.scss
  src/assets/Sass/project/popUp/_popUp.scss
  src/assets/Sass/report/_buttonFreela.scss
  src/assets/Sass/report/_descriptionFreela.scss
  src/assets/Sass/report/_reportFreela.scss
  src/assets/Sass/report/_titleFreela.scss
  src/assets/Sass/report/_titleProject.scss
  src/components/configProfile/ConfigProfile.vue
  src/components/configProfile/SideBar.vue
  src/components/configProfile/personalInformation/SkillsTable.vue
  src/components/default/header/DefaultHeader.vue
Labels: enhancement, refactor

#175 Refactor 132
  src/assets/Sass/default/header/_ListSmallScreens.scss
  src/assets/Sass/default/header/_hambugerButton.scss
  src/assets/Sass/default/header/_headerContainer.scss
  src/assets/Sass/default/header/_leftSide.scss
  src/assets/Sass/default/header/_rightSide.scss
  src/components/default/header/HamburgerButton.vue
  src/components/default/header/HeaderIcons.vue
  src/components/default/header/LeftSide.vue
  src/components/default/header/ListSmallScreens.vue
  src/components/default/header/RightSide.vue
Labels: refactor

#176 Dev
  src/assets/Sass/default/header/_ListSmallScreens.scss
  src/assets/Sass/default/header/_hambugerButton.scss
  src/assets/Sass/default/header/_headerContainer.scss
  src/assets/Sass/default/header/_leftSide.scss
  src/assets/Sass/default/header/_rightSide.scss
  src/components/default/header/HamburgerButton.vue
  src/components/default/header/HeaderIcons.vue
  src/components/default/header/LeftSide.vue
  src/components/default/header/ListSmallScreens.vue
  src/components/default/header/RightSide.vue
Labels: enhancement

#180 REFACTOR: Upgrade codes and add responsiveness #179
  src/assets/Sass/freelancer/_FreelaCardResp.scss
  src/assets/Sass/freelancer/_freelancer.scss
  src/assets/Sass/freelancer/_freelancerCard.scss
  src/assets/Sass/freelancer/_searchAreaResp.scss
  src/components/freelancer/CardsArea.vue
  src/components/freelancer/FreelancerCard.vue
  src/components/freelancer/SearchArea.vue
Labels: refactor

#177 FIX: Adjust in responsiveness 320px and 425px #148.
  src/assets/Sass/configProfile/_personalInformation.scss
  src/assets/Sass/configProfile/_sideBar.scss
  src/assets/Sass/configProfile/_skillsTable.scss
Labels: enhancement, refactor

#185 FIX: Adjust in responsiveness in height #139.
  src/assets/Sass/home/_freelaClient.scss
Labels: bug, enhancement, refactor

#186 REFACTOR: proposal page responsiveness #161
  src/assets/Sass/payment/inputs/_inputNumber.scss
  src/assets/Sass/payment/inputs/_inputText.scss
  src/assets/Sass/proposal/skills/_skillsTable.scss
  src/assets/Sass/proposal/skills/_tableSkills.scss
  src/assets/Sass/proposal/skills/_titleSkills.scss
  src/components/proposal/ProposalPage.vue
  src/components/proposal/inputs/InputNumberProposal.vue
  src/components/proposal/inputs/InputPayment.vue
  src/components/proposal/inputs/InputSelectProposal.vue
  src/components/proposal/inputs/InputTextProposal.vue
  src/components/proposal/inputs/InputsProposal.vue
  src/components/proposal/send/SendProposal.vue
  src/components/proposal/title/TitleProposal.vue
Labels: enhancement

#189 FIX: Subscription plan page responsiveness #179
  src/assets/Sass/plans/_subscriptionPlans.scss
  src/assets/Sass/plans/_subscriptionPlansResponsive.scss
  src/components/plans/subscriptionsPlans.vue
Labels: refactor

#191 Refactor 139
  src/assets/Sass/dashboard/_dashboardPage.scss
Labels: bug, enhancement, refactor

#192 fix-190
  src/stores/auth/auth.js
  src/stores/auth/signUp.js
  src/stores/perfil/infoPopUpPerfil.js
Labels: bug

#195 Feat 194
  package-lock.json
  package.json
  src/assets/Sass/home/_animation.scss
  src/assets/Sass/home/_headerHome.scss
  src/assets/Sass/home/_home.scss
  src/assets/images/Home/animation.gif
  src/assets/images/Home/animation.webm
  src/assets/images/home-test/applight-wave.svg
  src/assets/images/home-test/appstore.png
  src/assets/images/home-test/arrow-left.png
  src/assets/images/home-test/arrow-right.png
  src/assets/images/home-test/iphone-screen-with-shadow.png
  src/assets/images/home-test/iphone-screen.png
  src/assets/images/home-test/logo-black.png
  src/assets/images/home-test/logo.png
  src/assets/images/home-test/pattern.png
  src/assets/images/home-test/playstore.png
  src/assets/images/home-test/user1.jpg
  src/assets/images/home-test/user2.jpg
  src/assets/images/home-test/user3.jpg
  src/assets/images/home-test/video-bg.jpg
  src/views/global/HomeView.vue
Labels: enhancement

#203 feat-153
  package-lock.json
  package.json
  src/App.vue
  src/assets/Sass/chat/_chatView.scss
  src/assets/Sass/chat/chatMessage/_headerContact.scss
  src/assets/Sass/chat/chatMessage/_messages.scss
  src/assets/Sass/chat/chatMessage/_sendMessage.scss
  src/assets/Sass/chat/contacts/_asideContacts.scss
  src/assets/Sass/chat/contacts/_buttonSearch.scss
  src/assets/Sass/chat/contacts/_contactUser.scss
  src/assets/Sass/chat/contacts/_foundContacts.scss
  src/assets/Sass/configProfile/_sideBar.scss
  src/assets/Sass/configProfile/_skillsTable.scss
  src/assets/Sass/dashboard/projects/projectProgress/_cardProject.scss
  src/assets/Sass/default/header/_rightSide.scss
  src/assets/Sass/home/_freelaClient.scss
  src/assets/Sass/home/_headerHome.scss
  src/assets/Sass/project/_project.scss
  src/assets/images/chat/arrow-down.png
  src/assets/images/chat/close.png
  src/assets/images/chat/read.png
  src/assets/images/chat/trash.png
  src/assets/images/chat/trembo-1920.jpg
  src/assets/images/chat/trembo.jpeg
  src/assets/images/chat/unread.png
  src/assets/images/dashboard/user.png
  src/components/chat/AsideContacts.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/chatMessage/HeaderContact.vue
  src/components/chat/chatMessage/MessageReceived.vue
  src/components/chat/chatMessage/MessageSent.vue
  src/components/chat/chatMessage/MessagesUser.vue
  src/components/chat/chatMessage/PopUpImageSelect.vue
  src/components/chat/chatMessage/SendMessage.vue
  src/components/chat/contacts/ButtonSearch.vue
  src/components/chat/contacts/ContactUser.vue
  src/components/chat/contacts/FoundContacts.vue
  src/components/configProfile/confirmation/CodeVerification.vue
  src/components/dashboard/profile/AboutMe.vue
  src/components/dashboard/profile/LogoName.vue
  src/components/default/header/RightSide.vue
  src/components/index.js
  src/layouts/default/DefaultLayout.vue
  src/plugins/axios.js
  src/services/auth/auth.js
  src/services/chat/chat.js
  src/services/perfil/perfil.js
  src/stores/auth/signUp.js
  src/stores/chat/chat.js
  src/stores/chat/searchChat.js
  src/stores/perfil/perfil.js
  src/views/chat/ChatView.vue
  src/views/global/DashboardView.vue
Labels: enhancement

#199 REFACTOR: Add new responsiveness component finish payment #173.
  src/assets/Sass/payment/_paymentConfirm.scss
  src/router/index.js
Labels: refactor

#201 Feat 200
  src/assets/Sass/default/footer/_logoAndIcons.scss
  src/assets/images/QRCode.png
  src/components/index.js
  src/components/payment/MethodsPayment.vue
  src/components/payment/methods/AddressUser.vue
  src/components/payment/methods/CardMethod.vue
  src/components/payment/methods/QRCode.vue
  src/components/registerProject/projectRegistration/RegisterOption2.vue
  src/router/index.js
  src/views/payment/MethodsPaymentView.vue
Labels: enhancement, help wanted

#204 Feat 202
  package-lock.json
  package.json
  src/assets/Sass/finances/_finances.scss
  src/assets/Sass/finances/_graphFinance.scss
  src/assets/Sass/finances/_textLeft.scss
  src/components/finances/GraphFinance.vue
  src/components/finances/TextLeft.vue
  src/router/index.js
  src/views/finances/FinancesView.vue
Labels: enhancement

#209 feat-153
  package-lock.json
  src/assets/Sass/configProfile/_sideBar.scss
  src/assets/Sass/configProfile/_skillsTable.scss
  src/assets/Sass/default/header/_rightSide.scss
  src/assets/Sass/home/_home.scss
  src/components/default/header/LeftSide.vue
  src/plugins/axios.js
  src/stores/chat/chat.js
  src/views/global/HomeView.vue
Labels: enhancement
